<h1>About Us</h1>
<div id="homeDesc">
<p>Easyshare is a sharing ownership of individual assets by a group of like-minded  people which provides facility to build up, assemble, stimulate and run the  group. Valuable assets which are of high cost and they are not fully utilized  by an owner. So Easyshare helps to share cost and maintenance of the asset. Easyshare  assure maximum availability and fair usage of the asset between group members.</p>
 <p>You can show your asset as a <a href="index.php?process=edit_record">listing</a> here, So people can see it and inspire to set up a group. For this you need to <a href="index.php?process=signin">register</a> here. Unregistered  people can see other listing and send request to the owner of that listing to  create the group as well.</p>
<p>  Registered  User will have <a href="index.php?process=myAccount">My Account</a> page which gives facility to change account details  of the user, options to change and delete existing listings, option to create a  new group, options to manage and end the existing group(s) of the user.</p>
<p>  After  setting up or joining a group, all group members are ready to start enjoying  the asset. Each member will have My Group page which gives information about  their membership status, booking information, asset usage, and their invoice  list with view-print-download facility and financial summary of the group. This  page also facilitates to book new booking, edit and delete existing with online  calendar unique to your asset.</p>
<p>  Each  group will have Group administrator, Group finance controller and Group maintenance  controller. They will have Manage Group, Group Finance and Group Maintenance  pages respectively.</p>
<p>  Manage  Group page will give administration right to the user. On this page he/she will  have all users booking information as a admin log, list of all members,  facility to add new member, options to set and change booking rules and usage  monitors.</p>
<p>  Group Finance  page shows all financial transaction of group members, invoice and payment  lists separately. It also gives facility to create new single invoice or  payment and to set up regular invoice or payment. Billing preferences for the  group can be set here.</p>
<p>  Group Maintenance  page gives facility to set up schedules (kind of reminder) based on calendar  and usage monitor. I also allows to book maintenance periods on the live  calendar. Booking can overwrite the existing user&rsquo;s booking(s).</p>
</div>